spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:~/.hogwarts/persistence/hogwarts
    username: test
    password: test
    driver-class-name: org.h2.Driver
